on: 
  push:
    tags:
      - 'v*'
name: release-build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Checkout tag
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        tag_name="${GITHUB_REF##*/}"
        echo Tag $tag_name
        git checkout $tag_name
    - name: Build
      run: |
        make geosite.dat geoip.dat
        make release -j$(nproc)
        set -x
        assets=()
        for asset in ./*.zip; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create -p -d "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload binary
      uses: actions/upload-artifact@v1
      with:
        name: dist-release
        path: ./bin